-- Adiciona a categoria 'floral' aos itens de mobiliário que são flores
-- Baseado em termos comuns no nome do item

UPDATE public.inventory_items
SET category = 'floral'
WHERE type = 'furniture'
  AND (
    LOWER(name) LIKE '%flor%'
    OR LOWER(name) LIKE '%rosa%'
    OR LOWER(name) LIKE '%lírio%'
    OR LOWER(name) LIKE '%lirio%'
    OR LOWER(name) LIKE '%orquídea%'
    OR LOWER(name) LIKE '%orquidea%'
    OR LOWER(name) LIKE '%girassol%'
    OR LOWER(name) LIKE '%cravo%'
    OR LOWER(name) LIKE '%margarida%'
    OR LOWER(name) LIKE '%hibisco%'
    OR LOWER(name) LIKE '%peônia%'
    OR LOWER(name) LIKE '%peonia%'
    OR LOWER(name) LIKE '%daliam%'
    OR LOWER(name) like '%tulipa%'
    OR LOWER(name) LIKE '%arranjo%'
    OR LOWER(name) LIKE '%buquê%'
    OR LOWER(name) LIKE '%buque%'
    OR LOWER(name) LIKE '%floreira%'
    OR LOWER(name) LIKE '%planta%'
    OR LOWER(name) LIKE '%verde%'
    OR LOWER(name) LIKE '%folhagem%'
    OR LOWER(name) LIKE '%samambaia%'
    OR LOWER(name) LIKE '%palmeira%'
    OR LOWER(name) LIKE '%vaso%'
    OR LOWER(name) LIKE '%centerpiece%'
    OR LOWER(name) LIKE '%decoração floral%'
    OR LOWER(name) LIKE '%decoracao floral%'
    OR LOWER(notes) LIKE '%flor%'
    OR LOWER(notes) LIKE '%arranjo%'
    OR LOWER(notes) LIKE '%buquê%'
    OR LOWER(notes) LIKE '%buque%'
  );
