ALTER TABLE public.accounts_payable
ADD COLUMN IF NOT EXISTS discount NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS interest NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS fine NUMERIC(12,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS document_number TEXT;
